package com.barnizgallery.backend.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.barnizgallery.backend.dto.ThreeDModelResponse;
import com.barnizgallery.backend.service.ThreeDModelService;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;

/**
 * 3D model of an artwork, generated by Hyper3D Rodin (Adapter pattern).
 */
@RestController
@RequestMapping("/api/artworks/{id}/model")
@Tag(name = "3D models")
public class ThreeDModelController {

    private final ThreeDModelService threeDModelService;

    public ThreeDModelController(ThreeDModelService threeDModelService) {
        this.threeDModelService = threeDModelService;
    }

    @GetMapping
    public ThreeDModelResponse findByArtwork(@PathVariable Integer id) {
        return threeDModelService.findByArtwork(id);
    }

    @PostMapping("/generate")
    @Operation(summary = "Send the photos to Hyper3D (503 if disabled, 409 if already completed)")
    public ThreeDModelResponse generate(@PathVariable Integer id) {
        return threeDModelService.generate(id);
    }

    @PostMapping("/refresh")
    @Operation(summary = "Check the Hyper3D status and save the GLB URL when it is done")
    public ThreeDModelResponse refresh(@PathVariable Integer id) {
        return threeDModelService.refresh(id);
    }
}
